### ISSUE TITLE
Sorry - Request

### ISSUE THREAD

**Issue by BruceSackett** [technion/maia_mailguard#40]
Are there any basic instructions on upgrading from 1.02c to current?  I'm very excited to see this, and hope to be able to move forward!

If you have rough instructions, I could look at trying to flesh them out for you as an expansion.

**Comment by einheit** [comment]
I don't know of any specific documentation, but there is a db upgrade
script in the /admin directory of the maia document root.

For us it was mostly just a wholesale swap of old for new. For the web
piece, we installed the new php tree in a directory alongside the old one
and used symlinks to point to the one we wanted to use. Other than that, it
was just a matter of making sure maiad (which replaced amavis) was happy,
along with clamd and freshclam, checking logs etc if anything didn't start.
The usual devops stuff.

J




ᐧ

**Comment by technion** [comment]
Unfortunately there isn't a really great method of beyond a wholesale move to a new server.

The problem is, anything old enough to be running the original maia is going to have dead and unsupported versions of PHP, and tell a similar story on supporting infrastructure.

I can't see the sense in taking a five to ten year old OS install and attempting to leverage an upgraded maia onto it. You can of course, try your luck with the methods above.

There is no automated database upgrade script from 1.0.2c to the current version, however, the only change I have made, and the only db change in a long time, is to increase the size of the password field. You should be able to do this live with a simple alter command.
