### ISSUE TITLE
Does not exists amavisd-maia file

### ISSUE THREAD

**Issue by reztarter** [technion/maia_mailguard#77]
In official wiki documentation [](http://www.maiamailguard.com/maia/wiki/Install) in point 10.  Install amavisd-maia mentioned: "The amavisd-maia file in the Maia Mailguard distribution is a specially-patched version of amavisd-new 2.2.1.". But amavisd-maia file does not exists in distribution. Only file maiad exists in the root folder.

**Comment by technion** [comment]
What "official wiki" are you referring to?

**Comment by reztarter** [comment]
http://www.maiamailguard.com/maia/wiki/Install

**Comment by technion** [comment]
Unfortunately that website is old enough that it doesn't reflect the current codebase. To be clear, this service was just named "maiad" since I first copied the codebase.

https://github.com/technion/maia_mailguard/commit/2706e5ce3a079152fa169c739e705acae719861a#diff-f9947d77b9419514345e64bc066149a4

I'm afraid I can only suggest substituting the modern service name when appropriate.
